import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Gas Saver</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex text-center h-screen">
        <p className="flex text-white text-center items-center justify-center text-7xl font-extrabold w-full">
          Hello Next Js 👋
        </p>
      </main>
    </>
  );
}
